detail component
CodeSpace-Academy/ASE_2023_GROUP_F pull request #46
Opened 2023-10-12 09:49 UTC by Akido123

merged instructions and ingredients components into detail component

2023-10-12 10:31 UTC, chemonique approved these changes

2023-10-12 11:06 UTC, Kenneth-Ngcobo requested changes
Please remove dummy data, keep it local for testing.
details.css should be details.module.css

2023-10-13 07:17 UTC, Renzo-codespace commented on components/description/details.css
Rather delete the file than committing and empty one.

2023-10-13 07:18 UTC, Renzo-codespace commented on components/instructions/instructions.js
Please delete unused code rather than commenting it out.

2023-10-13 07:19 UTC, Renzo-codespace reviewed
Please update your branch!
Dummy data will have to be deleted as soon as the db connection is live.
The rest looks great so far!

2023-10-16 09:53 UTC, chemonique reviewed
delete the empty CSS files, remove dummy data

2023-10-16 20:16 UTC, closed without merging